from pathlib import Path

root = Path(__file__).resolve().parents[1]

# Fix the missing public route that caused the 404 from "Nouvelle demande".
app = root / "client/src/App.tsx"
s = app.read_text()
s = s.replace('    <Route path="/partenaires" component={Home} />\n', '    <Route path="/partenaires" component={Home} />\n    <Route path="/contact" component={Home} />\n')
app.write_text(s)

home = root / "client/src/pages/Home.tsx"
s = home.read_text()

# Add a reusable contextual help bubble for modal/sub-window guidance.
needle = 'function Field({ label, placeholder, type = "text", value, onChange }: { label: string; placeholder: string; type?: string; value?: string; onChange?: (value: string) => void }) {'
insert = '''function InfoBubble({ title, text }: { title: string; text: string }) {\n  const [open, setOpen] = useState(false);\n  return <div className="relative">\n    <button type="button" onClick={() => setOpen(value => !value)} aria-label={`Aide : ${title}`} aria-expanded={open} className="grid size-9 place-items-center rounded-full border border-amber-200 bg-amber-50 text-sm font-black text-amber-700 shadow-sm transition hover:bg-amber-100 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-200">?</button>\n    {open && <div role="status" className="absolute right-0 top-11 z-[100] w-72 rounded-2xl border border-border bg-card p-4 text-left text-xs leading-5 text-muted-foreground shadow-2xl">\n      <p className="font-bold text-foreground">{title}</p><p className="mt-1">{text}</p>\n    </div>}\n  </div>;\n}\n'''
if 'function InfoBubble' not in s:
    s = s.replace(needle, insert + needle)

# Let the Studies catalogue open the same secure request workflow as Services.
s = s.replace('  const [selected, setSelected] = useState<Program | null>(null);\n', '  const [selected, setSelected] = useState<Program | null>(null);\n  const [studyNeed, setStudyNeed] = useState<string | null>(null);\n  const [studyStep, setStudyStep] = useState<"detail" | "assessment" | "auth">("auth");\n')
s = s.replace('  return <PageWrap><Header locale={locale} setLocale={setLocale} /><main><section', '  return <PageWrap><Header locale={locale} setLocale={setLocale} /><main><section', 1)
# Add custom-program entry beside the existing contact action.
s = s.replace('<Button onClick={() => setLocation("/connexion")} className="w-fit rounded-full">{copy.contactIcx}<ArrowRight /></Button>', '<div className="flex flex-wrap gap-2"><Button onClick={() => setStudyNeed("Proposer un programme d’études personnalisé")} className="w-fit rounded-full">Proposer un programme<ArrowRight /></Button><Button variant="outline" onClick={() => setLocation("/connexion")} className="w-fit rounded-full">{copy.contactIcx}<ArrowRight /></Button></div>', 1)
s = s.replace('onApply={() => { setSelected(null); setLocation("/connexion"); }} />}</PageWrap>', 'onApply={() => { setStudyNeed(`Candidature · ${selected.field} · ${selected.university}`); setSelected(null); setStudyStep("auth"); }} />}</PageWrap>', 1)
# The previous replacement leaves the help workflow outside the page only if explicitly inserted.
s = s.replace('</section></main>{selected && <ProgramDialog program={selected} onClose={() => setSelected(null)} onApply={() => { setStudyNeed(`Candidature · ${selected.field} · ${selected.university}`); setSelected(null); setStudyStep("auth"); }} />}</PageWrap>', '</section></main>{selected && <ProgramDialog program={selected} onClose={() => setSelected(null)} onApply={() => { setStudyNeed(`Candidature · ${selected.field} · ${selected.university}`); setSelected(null); setStudyStep("auth"); }} />}{studyNeed && <ServiceWorkflow service={serviceBySlug.etudes} locale={locale} need={studyNeed} step={studyStep} setStep={setStudyStep} onClose={() => setStudyNeed(null)} setLocation={setLocation} />}</PageWrap>', 1)

# Add contextual help to program/service dialogs and service sub-windows.
s = s.replace('<button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-muted text-muted-foreground" aria-label="Close"><X className="size-4" /></button></div><p className="mt-7', '<div className="flex items-center gap-2"><InfoBubble title="Dossier d’études" text="Cette fenêtre présente les informations utiles et les pièces principales avant de commencer votre demande." /><button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-muted text-muted-foreground" aria-label="Close"><X className="size-4" /></button></div></div><p className="mt-7', 1)
s = s.replace('<Link href="/" className="mb-12 inline-flex', '<div className="mb-6 flex justify-end"><InfoBubble title={view.label} text="Utilisez les onglets et les actions pour préciser votre besoin. La bulle indique les informations utiles à cette étape." /></div><Link href="/" className="mb-12 inline-flex', 1)

# Enrich the common secure workflow for academic applications and guardian contacts.
s = s.replace('  const [identity, setIdentity] = useState({ username: "", country: "", phoneCode: "+40", phone: "" });', '  const [identity, setIdentity] = useState({ username: "", country: "", phoneCode: "+40", phone: "", guardianPhoneCode: "+40", guardianPhone: "" });\n  const [isMinor, setIsMinor] = useState(false);\n  const [studyTarget, setStudyTarget] = useState({ country: "", university: "", program: "" });')
s = s.replace('  const [attachments, setAttachments]', '  const studyUniversities = Array.from(new Set(programs.filter(program => !studyTarget.country || program.country === studyTarget.country).map(program => program.university)));\n  const [attachments, setAttachments]')
s = s.replace('setIdentity(d.identity||{username:"",country:""});setAttachments', 'setIdentity(d.identity||{username:"",country:"",phoneCode:"+40",phone:"",guardianPhoneCode:"+40",guardianPhone:""});setIsMinor(Boolean(d.isMinor));setStudyTarget(d.studyTarget||{country:"",university:"",program:""});setAttachments')
s = s.replace('localStorage.setItem(draftKey,JSON.stringify({answer,message,identity,attachments,scheduledAt}))', 'localStorage.setItem(draftKey,JSON.stringify({answer,message,identity,isMinor,studyTarget,attachments,scheduledAt}))')
s = s.replace('message: `${identity.username ? `[${copy.username}: ${identity.username}] ` : ""}${identity.country ? `[${copy.country}: ${identity.country}] ` : ""}${identity.phone ? `[Téléphone: ${identity.phoneCode} ${identity.phone}] ` : ""}${message || `${need} — ${answer}`}`', 'message: `${identity.username ? `[${copy.username}: ${identity.username}] ` : ""}${identity.country ? `[${copy.country}: ${identity.country}] ` : ""}${identity.phone ? `[Téléphone: ${identity.phoneCode} ${identity.phone}] ` : ""}${service.architecture === "academic" ? `[Pays d’étude: ${studyTarget.country || "à préciser"}] [Université: ${studyTarget.university || "à préciser"}] [Programme: ${studyTarget.program || need}] ` : ""}${isMinor ? `[Demandeur mineur · garant/interlocuteur: ${identity.guardianPhoneCode} ${identity.guardianPhone}] ` : ""}${message || `${need} — ${answer}`}`')
# Add academic target and minor/guardian fields before the document list.
marker = '<div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-900/50 dark:bg-amber-950/20"><p className="text-xs font-bold uppercase tracking-[0.12em] text-amber-800 dark:text-amber-200">Documents utiles pour ce service</p>'
academic = '<>{service.architecture === "academic" && <div className="space-y-3 rounded-xl border border-emerald-200 bg-emerald-50/60 p-4 dark:border-emerald-900/50 dark:bg-emerald-950/20"><p className="text-xs font-bold uppercase tracking-[0.12em] text-emerald-800 dark:text-emerald-200">Projet d’études</p><div className="grid gap-3 sm:grid-cols-2"><select value={studyTarget.country} onChange={event => setStudyTarget(current => ({ ...current, country: event.target.value, university: "" }))} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="">Choisir un pays</option>{countries.slice(1).map(item => <option key={item}>{item}</option>)}</select><select value={studyTarget.university} onChange={event => setStudyTarget(current => ({ ...current, university: event.target.value }))} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="">Choisir une université</option>{studyUniversities.map(item => <option key={item}>{item}</option>)}</select></div><input value={studyTarget.program} onChange={event => setStudyTarget(current => ({ ...current, program: event.target.value }))} placeholder="Programme souhaité (ou proposition libre)" className="h-10 w-full rounded-xl border border-input bg-background px-3 text-sm" /><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={isMinor} onChange={event => setIsMinor(event.target.checked)} />Le demandeur est mineur</label>{isMinor && <div className="grid gap-3 sm:grid-cols-[.42fr_1fr]"><select value={identity.guardianPhoneCode} onChange={event => setIdentity(current => ({ ...current, guardianPhoneCode: event.target.value }))} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option>+40</option><option>+33</option><option>+1</option><option>+44</option><option>+221</option><option>+225</option><option>+237</option><option>+243</option><option>+212</option></select><input required value={identity.guardianPhone} onChange={event => setIdentity(current => ({ ...current, guardianPhone: event.target.value }))} placeholder="Téléphone du garant ou interlocuteur" className="h-10 rounded-xl border border-input bg-background px-3 text-sm" /></div>}</div>}</> ' + marker
if marker in s:
    s = s.replace(marker, academic, 1)
# Add help bubble in workflow header.
s = s.replace('<button onClick={onClose} className="absolute right-5 top-5 z-10', '<div className="absolute right-16 top-5 z-10"><InfoBubble title="Avant l’envoi" text="Les documents requis sont listés avant l’envoi. Un dossier transmis ne peut plus être modifié depuis le portail ; contactez ICX pour demander une correction." /></div><button onClick={onClose} className="absolute right-5 top-5 z-10', 1)

# Add help bubble to partnership dialog and allow a selectable phone code.
s = s.replace('  const [form, setForm] = useState({ companyName: "", contactName: "", email: user?.email || "", phone: "", needs: "" });', '  const [form, setForm] = useState({ companyName: "", contactName: "", email: user?.email || "", phoneCode: "+40", phone: "", needs: "" });')
s = s.replace('<button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-muted" aria-label="Close"><X className="size-4" /></button>', '<div className="flex items-center gap-2"><InfoBubble title="Partenariat" text="Présentez votre organisation, les pays concernés, vos besoins et le calendrier souhaité. L’équipe ICX vous recontactera pour la qualification." /><button onClick={onClose} className="grid size-9 place-items-center rounded-full bg-muted" aria-label="Close"><X className="size-4" /></button></div>', 1)
s = s.replace('<Field label="Téléphone" placeholder="+40 ..." value={form.phone} onChange={value => setForm(prev => ({ ...prev, phone: value }))} />', '<div className="grid grid-cols-[.42fr_1fr] gap-2"><select aria-label="Code téléphonique" value={form.phoneCode} onChange={event => setForm(prev => ({ ...prev, phoneCode: event.target.value }))} className="h-11 rounded-xl border border-input bg-background px-3 text-sm"><option>+40</option><option>+33</option><option>+1</option><option>+44</option><option>+221</option><option>+225</option><option>+237</option><option>+243</option><option>+212</option></select><Field label="Téléphone" placeholder="Numéro" value={form.phone} onChange={value => setForm(prev => ({ ...prev, phone: value }))} /></div>', 1)
s = s.replace('mutation.mutate(form)', 'mutation.mutate({ ...form, phone: form.phone ? `${form.phoneCode} ${form.phone}` : "" })', 1)

home.write_text(s)

# Add richer admin-side request filtering and notification deletion to the actual separate admin console.
admin = root / "client/src/admin/AdminConsole.tsx"
s = admin.read_text()
s = s.replace('  const [statusFilter, setStatusFilter] = useState("Tous les statuts");', '  const [statusFilter, setStatusFilter] = useState("Tous les statuts");\n  const [priorityFilter, setPriorityFilter] = useState("Toutes les priorités");\n  const [serviceFilter, setServiceFilter] = useState("Tous les services");\n  const [countryFilter, setCountryFilter] = useState("Tous les pays");\n  const [needFilter, setNeedFilter] = useState("");\n  const [sortBy, setSortBy] = useState("recent");')
s = s.replace('  const sendNotification = trpc.admin.sendNotification.useMutation({', '  const deleteNotification = trpc.admin.deleteNotification.useMutation({ onSuccess: async () => { await utils.admin.notifications.invalidate(); toast.success("Notification supprimée."); }, onError: error => toast.error(error.message) });\n  const sendNotification = trpc.admin.sendNotification.useMutation({')
old = '''        const matchesStatus =\n          statusFilter === "Tous les statuts" || item.status === statusFilter;\n        return matchesSearch && matchesStatus;'''
new = '''        const matchesStatus = statusFilter === "Tous les statuts" || item.status === statusFilter;\n        const matchesPriority = priorityFilter === "Toutes les priorités" || item.priority === priorityFilter;\n        const matchesService = serviceFilter === "Tous les services" || item.serviceKey === serviceFilter;\n        const matchesCountry = countryFilter === "Tous les pays" || item.country === countryFilter;\n        const matchesNeed = !needFilter.trim() || `${item.message || ""} ${item.serviceKey}`.toLowerCase().includes(needFilter.trim().toLowerCase());\n        return matchesSearch && matchesStatus && matchesPriority && matchesService && matchesCountry && matchesNeed;'''
s = s.replace(old, new)
s = s.replace('[requestRows, requestSearch, statusFilter]\n  );', '[requestRows, requestSearch, statusFilter, priorityFilter, serviceFilter, countryFilter, needFilter]\n  );')
# Add admin filter controls after the status select.
status_block = '''                    <select\n                      value={statusFilter}\n                      onChange={event => setStatusFilter(event.target.value)}\n                      className="mt-3 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"\n                    >\n                      <option>Tous les statuts</option>\n                      {STATUSES.map(status => (\n                        <option key={status}>{status}</option>\n                      ))}\n                    </select>'''
filters = status_block + '''\n                    <div className="mt-3 grid gap-2 sm:grid-cols-2">\n                      <select value={priorityFilter} onChange={event => setPriorityFilter(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"><option>Toutes les priorités</option>{PRIORITIES.map(priority => <option key={priority} value={priority}>{priority === "urgent" ? "Urgente" : priority === "high" ? "Haute" : priority === "low" ? "Basse" : "Normale"}</option>)}</select>\n                      <select value={serviceFilter} onChange={event => setServiceFilter(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"><option>Tous les services</option>{Array.from(new Set(requestRows.map(item => item.serviceKey))).sort().map(service => <option key={service}>{service}</option>)}</select>\n                      <select value={countryFilter} onChange={event => setCountryFilter(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"><option>Tous les pays</option>{Array.from(new Set(requestRows.map(item => item.country).filter(Boolean))).sort().map(country => <option key={country}>{country}</option>)}</select>\n                      <select value={sortBy} onChange={event => setSortBy(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold"><option value="recent">Plus récentes</option><option value="priority">Priorité / urgence</option><option value="oldest">Plus anciennes</option></select>\n                    </div>\n                    <input value={needFilter} onChange={event => setNeedFilter(event.target.value)} placeholder="Besoin ou programme d’études…" className="mt-2 h-9 w-full rounded-lg border border-slate-200 bg-white px-3 text-xs" />'''
s = s.replace(status_block, filters, 1)
# Sort filtered rows by urgency/priority, with explicit priority ordering.
s = s.replace('  const selectedMail =', '  const priorityOrder = { urgent: 4, high: 3, normal: 2, low: 1 } as const;\n  const sortedVisibleRequests = [...visibleRequests].sort((a, b) => sortBy === "oldest" ? new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime() : sortBy === "priority" ? (priorityOrder[b.priority as keyof typeof priorityOrder] || 0) - (priorityOrder[a.priority as keyof typeof priorityOrder] || 0) : new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());\n  const selectedMail =')
s = s.replace('visibleRequests.map(item => (', 'sortedVisibleRequests.map(item => (', 1)
s = s.replace('!requests.isLoading && visibleRequests.length === 0', '!requests.isLoading && sortedVisibleRequests.length === 0', 1)
# Add delete button to notification history cards.
s = s.replace('{item.content}\n                          </p>\n                        </article>', '{item.content}\n                          </p>\n                          <button type="button" onClick={() => deleteNotification.mutate({ id: item.id })} className="mt-3 text-xs font-bold text-rose-600 hover:underline">Supprimer la notification</button>\n                        </article>', 1)
admin.write_text(s)
