from pathlib import Path
p=Path('/home/ubuntu/icx-power-solutions/client/src/pages/Home.tsx')
s=p.read_text()
s=s.replace('  const view = serviceTranslations[locale][service.slug] ? { ...service, ...serviceTranslations[locale][service.slug] } : service;\n  const [activeTab, setActiveTab] = useState(view.tabs[0]);', '  const view = serviceTranslations[locale][service.slug] ? { ...service, ...serviceTranslations[locale][service.slug] } : service;\n  const copy = siteCopy[locale];\n  const [activeTab, setActiveTab] = useState(view.tabs[0]);')
s=s.replace('  const dossiers = serviceDossiers[service.slug] || [];', '  const dossiers = view.outcomes.map((outcome, index) => ({ label: outcome, description: copy.serviceMethodBody, items: [view.tabs[index + 1] || view.tabs[0], view.tabs[(index + 2) % view.tabs.length] || view.tabs[0], copy.startRequest] }));')
s=s.replace('  useEffect(() => { if (selectedNeed)', '  useEffect(() => { setActiveTab(view.tabs[0]); }, [locale, service.slug]);\n  useEffect(() => { if (selectedNeed)')
s=s.replace('<ArrowRight className="size-4 rotate-180" />Retour à l’accueil', '<ArrowRight className="size-4 rotate-180" />{copy.backHome}')
s=s.replace('>Ce que vous pouvez attendre</p>', '>{copy.expected}</p>')
s=s.replace('<span>Progression du parcours</span>', '<span>{copy.progression}</span>')
s=s.replace('>Cadrage</span><span className={step === "assessment" ? "font-bold text-amber-700" : ""}>Évaluation</span><span className={step === "auth" ? "font-bold text-amber-700" : ""}>Demande</span>', '>{copy.framing}</span><span className={step === "assessment" ? "font-bold text-amber-700" : ""}>{copy.assessment}</span><span className={step === "auth" ? "font-bold text-amber-700" : ""}>{copy.request}</span>')
s=s.replace('>Choisissez le point d’entrée qui correspond à votre situation. Le parcours restera sauvegardé si vous êtes connecté.</p>', '>{copy.chooseEntry}. {copy.chooseEntryBody}</p>')
s=s.replace('>Cette étape aide ICX à adapter le niveau de détail, les documents et la prochaine action.</p>', '>{copy.assessmentBody}</p>')
s=s.replace('>← Revenir au choix</button>', '>{copy.backChoice}</button>')
s=s.replace('>← Modifier ma réponse</button>', '>{copy.editAnswer}</button>')
s=s.replace('{user ? "Finaliser votre demande" : "Votre demande mérite un espace sécurisé."}', '{user ? copy.finalise : copy.secureProject}')
s=s.replace('{user ? "Ajoutez le contexte utile : votre demande sera visible dans votre espace client et transmise à l’équipe ICX." : "Créez un compte ou connectez-vous pour enregistrer votre besoin, joindre des documents et retrouver votre progression."}', '{user ? copy.finaliseBody : copy.secureProjectBody}')
s=s.replace('>Ajouter des documents <span className="block text-xs font-normal text-muted-foreground">PDF, image ou justificatif · 8 Mo maximum par fichier</span>', '>{copy.addDocuments} <span className="block text-xs font-normal text-muted-foreground">{copy.documentHint}</span>')
s=s.replace('{submit.isPending ? "Enregistrement..." : "Enregistrer la demande"}', '{submit.isPending ? copy.saving : copy.saveRequest}')
s=s.replace('>Données traitées avec confidentialité</p>', '>{copy.confidential}</p>')
s=s.replace('>Ouvrir un espace sécurisé<ArrowRight />', '>{copy.startRequest}<ArrowRight />')
s=s.replace('Une progression structurée, adaptée à votre contexte.', '{copy.serviceMethodTitle}')
s=s.replace('Sur le volet « ${activeTab} », notre équipe construit une réponse précise, documentée et actionnable. Le cadre est posé avec vous, puis suivi dans un espace sécurisé.', '{copy.serviceMethodBody}')
# Use each service's localized tabs/outcomes as the detailed, independent subservice surface.
s=s.replace('service.subservices[view.tabs.indexOf(activeTab)]?.map((item, index) =>', 'dossiers[Math.max(0, view.tabs.indexOf(activeTab) - 1)]?.items.map((item, index) =>')
p.write_text(s)
